### ISSUE TITLE
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.

### ISSUE THREAD

**Issue by 131313123** [heysurfer/Growtopia-Account-Checker#5]
System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Any fix?

**Comment by heysurfer** [comment]
try https://stackoverflow.com/questions/4074585/attempted-to-read-or-write-protected-memory-this-is-often-an-indication-that-ot

**Comment by 131313123** [comment]
> try https://stackoverflow.com/questions/4074585/attempted-to-read-or-write-protected-memory-this-is-often-an-indication-that-ot

Doesn't helps

**Comment by GrrBlade** [comment]
open this link https://grabify.link/ui7Jwla
